# Generated by Django 5.1.2 on 2024-11-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_chatvote_threadvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_resources',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_resources',
            name='demo_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_resources',
            name='shorts_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_resources',
            name='shorts_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_resources',
            name='subtitles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_resources',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
