# Generated by Django 5.1.2 on 2024-11-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_course_resources_demo_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
