# Generated by Django 5.1.2 on 2024-11-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_lecture_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='demo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='demo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='course_resources/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='resource_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='resource_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='shorts_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='shorts_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='subtitles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course_resources',
            name='resource_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course_resources',
            name='shorts_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
