# Generated by Django 5.1.2 on 2024-11-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_lecture_demo_link_lecture_demo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_resources',
            name='demo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
