# Generated by Django 5.1.2 on 2024-11-23 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_alter_course_resources_demo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_resources',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='course_resources',
            name='demo_name',
        ),
    ]
