# Generated by Django 5.1.2 on 2024-11-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_course_resources_demo_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='demo_name',
        ),
    ]
