# Generated by Django 5.1.2 on 2024-11-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_remove_lecture_demo_link_remove_lecture_demo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='resource_link',
            new_name='audio_link',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='shorts_link',
            new_name='video_link',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='resource_file',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='resource_name',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='shorts_name',
        ),
        migrations.AddField(
            model_name='course_resources',
            name='quiz_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course_resources',
            name='quiz_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
